### ISSUE TITLE
Capturing audio segment from clip

### ISSUE THREAD

**Issue by okankop** [fuankarion/active-speakers-context#10]
Hi, to capture the audio part from the clip, you are subtracting the **audio_offset** at the calculation of audio_start and audio_end at the [L103](https://github.com/fuankarion/active-speakers-context/blob/a88f01e71100e442899ce0991c0e7c4e61a89c95/core/io.py#L103). Is it correct way of capturing audio part? I believe, we should not subtract audio_offset.

**Comment by fuankarion** [comment]
Hi, we need the audio offset because the timestamp in the ground-truth file  localizes the audio event in the full video, but is not suitable for the audio clips required by the STE. The offset contains the beginning timestamp of the audio clip this allows us to map the timestamp in the ground-truth file to the same location in the clip by subtracting the offset,
